;;; doom-one-faces.el --- doom-one 配色表 -*- lexical-binding: t; -*-
;;
;; 由 `make faces' 从本机 Doom 的 doom-themes 生成,不要手改。
;; 生成脚本与背景说明见 scripts/gen-faces.el。
;; 主题: doom-one   Emacs: 30.2   face 数: 1262

(defconst blog-doom-one-faces
  '((+fold-hideshow-folded-face :inherit font-lock-comment-face :weight light :background "#22252c" :box (:line-width -1 :style released-button))
    (Man-overstrike :inherit bold :foreground "#51afef")
    (Man-underline :inherit underline :foreground "#51afef")
    (TeX-error-description-error :inherit error :weight bold)
    (TeX-error-description-tex-said :inherit success :weight bold)
    (TeX-error-description-warning :inherit warning :weight bold)
    (agda2-highlight-bound-variable-face :inherit font-lock-variable-name-face)
    (agda2-highlight-coinductive-constructor-face :inherit font-lock-type-face)
    (agda2-highlight-datatype-face :inherit font-lock-type-face)
    (agda2-highlight-dotted-face :inherit font-lock-variable-name-face)
    (agda2-highlight-error-face :inherit font-lock-warning-face)
    (agda2-highlight-field-face :inherit font-lock-type-face)
    (agda2-highlight-function-face :inherit font-lock-function-name-face)
    (agda2-highlight-incomplete-pattern-face :inherit font-lock-warning-face)
    (agda2-highlight-inductive-constructor-face :inherit font-lock-type-face)
    (agda2-highlight-keyword-face :inherit font-lock-keyword-face)
    (agda2-highlight-macro-face :inherit font-lock-function-name-face)
    (agda2-highlight-module-face :inherit font-lock-variable-name-face)
    (agda2-highlight-number-face :inherit font-lock-string-face)
    (agda2-highlight-positivity-problem-face :inherit font-lock-warning-face)
    (agda2-highlight-postulate-face :inherit font-lock-type-face)
    (agda2-highlight-primitive-face :inherit font-lock-type-face)
    (agda2-highlight-primitive-type-face :inherit font-lock-type-face)
    (agda2-highlight-record-face :inherit font-lock-type-face)
    (agda2-highlight-string-face :inherit font-lock-string-face)
    (agda2-highlight-symbol-face :inherit font-lock-variable-name-face)
    (agda2-highlight-termination-problem-face :inherit font-lock-warning-face)
    (agda2-highlight-typechecks-face :inherit font-lock-warning-face)
    (agda2-highlight-unsolved-constraint-face :inherit font-lock-warning-face)
    (agda2-highlight-unsolved-meta-face :inherit font-lock-warning-face)
    (alert-high-face :inherit t :foreground "#ECBE7B")
    (alert-low-face :foreground "#3f444a")
    (alert-moderate-face :inherit t :foreground "#5B6268")
    (alert-trivial-face :foreground "#83898d")
    (alert-urgent-face :inherit t :foreground "#ff6c6b")
    (all-the-icons-blue :foreground "#51afef")
    (all-the-icons-blue-alt :foreground "#4db5bd")
    (all-the-icons-cyan :foreground "#46D9FF")
    (all-the-icons-cyan-alt :foreground "#46D9FF")
    (all-the-icons-dblue :foreground "#2257A0")
    (all-the-icons-dcyan :foreground "#5699AF")
    (all-the-icons-dgreen :foreground "#6a8546")
    (all-the-icons-dired-dir-face :foreground "#83898d")
    (all-the-icons-dmaroon :foreground "#8a549a")
    (all-the-icons-dorange :foreground "#985d32")
    (all-the-icons-dpink :foreground "#ff8281")
    (all-the-icons-dpurple :foreground "#76709d")
    (all-the-icons-dred :foreground "#b24b4a")
    (all-the-icons-dsilver :foreground "#52565c")
    (all-the-icons-dyellow :foreground "#a58556")
    (all-the-icons-green :foreground "#98be65")
    (all-the-icons-lblue :foreground "#85c7f3")
    (all-the-icons-lcyan :foreground "#7de4ff")
    (all-the-icons-lgreen :foreground "#b6d193")
    (all-the-icons-lmaroon :foreground "#d7a0e7")
    (all-the-icons-lorange :foreground "#e5a97e")
    (all-the-icons-lpink :foreground "#ffbcbc")
    (all-the-icons-lpurple :foreground "#c2bdea")
    (all-the-icons-lred :foreground "#ff9897")
    (all-the-icons-lsilver :foreground "#c5c6c8")
    (all-the-icons-lyellow :foreground "#f1d1a2")
    (all-the-icons-maroon :foreground "#c678dd")
    (all-the-icons-orange :foreground "#da8548")
    (all-the-icons-pink :foreground "#ff9f9e")
    (all-the-icons-purple :foreground "#a9a1e1")
    (all-the-icons-purple-alt :foreground "#4e5160")
    (all-the-icons-red :foreground "#ff6c6b")
    (all-the-icons-red-alt :foreground "#5b494e")
    (all-the-icons-silver :foreground "#95989b")
    (all-the-icons-yellow :foreground "#ECBE7B")
    (annotate-annotation :background "#2c3946" :foreground "#83898d")
    (annotate-annotation-secondary :background "#333a38" :foreground "#83898d")
    (annotate-highlight :background "#2c3946" :underline "#51afef")
    (annotate-highlight-secondary :background "#333a38" :underline "#98be65")
    (ansi-color-black :foreground "#282c34" :background "#282c34")
    (ansi-color-blue :foreground "#51afef" :background "#51afef")
    (ansi-color-bright-black :foreground "#3f444a" :background "#3f444a")
    (ansi-color-bright-blue :foreground "#6bbbf1" :background "#6bbbf1")
    (ansi-color-bright-cyan :foreground "#61deff" :background "#61deff")
    (ansi-color-bright-green :foreground "#a7c77c" :background "#a7c77c")
    (ansi-color-bright-magenta :foreground "#ce8ce2" :background "#ce8ce2")
    (ansi-color-bright-red :foreground "#ff8281" :background "#ff8281")
    (ansi-color-bright-white :foreground "#DFDFDF" :background "#DFDFDF")
    (ansi-color-bright-yellow :foreground "#eec78e" :background "#eec78e")
    (ansi-color-cyan :foreground "#46D9FF" :background "#46D9FF")
    (ansi-color-green :foreground "#98be65" :background "#98be65")
    (ansi-color-magenta :foreground "#c678dd" :background "#c678dd")
    (ansi-color-red :foreground "#ff6c6b" :background "#ff6c6b")
    (ansi-color-white :foreground "#bbc2cf" :background "#bbc2cf")
    (ansi-color-yellow :foreground "#ECBE7B" :background "#ECBE7B")
    (anzu-replace-highlight :background "#1B2229" :foreground "#ff6c6b" :weight bold :strike-through t)
    (anzu-replace-to :background "#1B2229" :foreground "#98be65" :weight bold)
    (avy-background-face :foreground "#5B6268")
    (avy-lead-face :background "#51afef" :foreground "#282c34" :distant-foreground "#bbc2cf" :weight bold)
    (avy-lead-face-0 :inherit avy-lead-face :background "#85c7f3")
    (avy-lead-face-1 :inherit avy-lead-face :background "#b9dff8")
    (avy-lead-face-2 :inherit avy-lead-face :background "#edf7fd")
    (bmkp-*-mark :foreground "#282c34" :background "#ECBE7B")
    (bmkp->-mark :foreground "#ECBE7B")
    (bmkp-D-mark :foreground "#282c34" :background "#ff6c6b")
    (bmkp-X-mark :foreground "#ff6c6b")
    (bmkp-a-mark :background "#ff6c6b")
    (bmkp-bad-bookmark :foreground "#282c34" :background "#ECBE7B")
    (bmkp-bookmark-file :foreground "#a9a1e1" :background "#21242b")
    (bmkp-bookmark-list :background "#21242b")
    (bmkp-buffer :foreground "#51afef")
    (bmkp-desktop :foreground "#282c34" :background "#a9a1e1")
    (bmkp-file-handler :background "#ff6c6b")
    (bmkp-function :foreground "#98be65")
    (bmkp-gnus :foreground "#da8548")
    (bmkp-heading :foreground "#ECBE7B")
    (bmkp-info :foreground "#46D9FF")
    (bmkp-light-autonamed :foreground "#21242b" :background "#46D9FF")
    (bmkp-light-autonamed-region :foreground "#21242b" :background "#ff6c6b")
    (bmkp-light-fringe-autonamed :foreground "#21242b" :background "#a9a1e1")
    (bmkp-light-fringe-non-autonamed :foreground "#21242b" :background "#98be65")
    (bmkp-light-mark :foreground "#282c34" :background "#46D9FF")
    (bmkp-light-non-autonamed :foreground "#282c34" :background "#a9a1e1")
    (bmkp-light-non-autonamed-region :foreground "#282c34" :background "#ff6c6b")
    (bmkp-local-directory :foreground "#282c34" :background "#a9a1e1")
    (bmkp-local-file-with-region :foreground "#ECBE7B")
    (bmkp-local-file-without-region :foreground "#5B6268")
    (bmkp-man :foreground "#a9a1e1")
    (bmkp-no-jump :foreground "#5B6268")
    (bmkp-no-local :foreground "#ECBE7B")
    (bmkp-non-file :foreground "#98be65")
    (bmkp-remote-file :foreground "#da8548")
    (bmkp-sequence :foreground "#51afef")
    (bmkp-su-or-sudo :foreground "#ff6c6b")
    (bmkp-t-mark :foreground "#a9a1e1")
    (bmkp-url :foreground "#51afef" :underline t)
    (bmkp-variable-list :foreground "#98be65")
    (bold :weight bold :foreground unspecified)
    (bold-italic :inherit (bold italic))
    (bookmark-face :background "#2c3946" :extend t)
    (calfw-annotation-face :foreground "#a9a1e1")
    (calfw-day-title-face :foreground "#bbc2cf" :weight bold)
    (calfw-default-content-face :foreground "#bbc2cf")
    (calfw-default-day-face :weight bold)
    (calfw-disable-face :foreground "#3f444a")
    (calfw-grid-face :foreground "#191b20")
    (calfw-header-face :foreground "#4894c9" :weight bold)
    (calfw-holiday-face :background "#21242b" :weight bold)
    (calfw-periods-face :foreground "#ECBE7B")
    (calfw-saturday-face :foreground "#d45f60" :weight bold)
    (calfw-sunday-face :foreground "#d45f60" :weight bold)
    (calfw-title-face :foreground "#51afef" :weight bold :height 2.0 :inherit variable-pitch)
    (calfw-today-face :weight bold)
    (calfw-today-title-face :foreground "#282c34" :background "#51afef" :weight bold)
    (calfw-toolbar-button-off-face :foreground "#73797e" :weight bold :inherit variable-pitch)
    (calfw-toolbar-button-on-face :foreground "#51afef" :weight bold :inherit variable-pitch)
    (centaur-tabs-active-bar-face :background "#51afef")
    (centaur-tabs-default :background "#21242b" :foreground "#21242b" :box unspecified)
    (centaur-tabs-modified-marker-selected :foreground "#51afef" :inherit centaur-tabs-selected)
    (centaur-tabs-modified-marker-unselected :foreground "#51afef" :inherit centaur-tabs-unselected)
    (centaur-tabs-selected :background "#282c34" :foreground "#bbc2cf" :box unspecified)
    (centaur-tabs-selected-modified :background "#282c34" :foreground "#4db5bd")
    (centaur-tabs-unselected :background "#21242b" :foreground "#5B6268" :box unspecified)
    (centaur-tabs-unselected-modified :background "#21242b" :foreground "#4db5bd")
    (cider-debug-code-overlay-face :background "#23272e")
    (cider-deprecated-face :background "#4f4942")
    (cider-enlightened-face :inherit cider-result-overlay-face :box (:color "#da8548" :line-width -1))
    (cider-enlightened-local-face :foreground "#da8548" :weight bold)
    (cider-error-highlight-face :inherit font-lock-warning-face :underline t)
    (cider-fringe-good-face :foreground "#98be65")
    (cider-instrumented-face :background "#52383f")
    (cider-result-overlay-face :background "#23272e" :box (:line-width -1 :color "#5B6268"))
    (cider-test-error-face :background "#da8548")
    (cider-test-failure-face :background "#683f44")
    (cider-test-success-face :foreground "#1B2229" :background "#98be65")
    (cider-traced-face :background "#2e4e5c")
    (cider-warning-highlight-face :inherit font-lock-warning-face :underline (:color "#ECBE7B"))
    (circe-fool :foreground "#83898d")
    (circe-highlight-nick-face :weight bold :foreground "#a9a1e1")
    (circe-my-message-face :weight bold)
    (circe-prompt-face :weight bold :foreground "#51afef")
    (circe-server-face :foreground "#5B6268")
    (company-box-candidate :foreground "#bbc2cf")
    (company-preview :foreground "#5B6268")
    (company-preview-common :background "#23272e" :foreground "#51afef")
    (company-preview-search :inherit company-tooltip-search)
    (company-scrollbar-bg :inherit tooltip)
    (company-scrollbar-fg :background "#51afef")
    (company-template-field :inherit match)
    (company-tooltip :inherit tooltip)
    (company-tooltip-annotation :foreground "#a9a1e1" :distant-foreground "#282c34")
    (company-tooltip-common :foreground "#51afef" :distant-foreground "#1B2229" :weight bold)
    (company-tooltip-mouse :background "#c678dd" :foreground "#282c34" :distant-foreground "#bbc2cf")
    (company-tooltip-search :background "#51afef" :foreground "#282c34" :distant-foreground "#bbc2cf" :weight bold)
    (company-tooltip-search-selection :background "#194178")
    (company-tooltip-selection :background "#2257A0" :weight bold)
    (compilation-column-number :inherit font-lock-comment-face)
    (compilation-error :inherit error :weight bold)
    (compilation-info :inherit success)
    (compilation-line-number :foreground "#51afef")
    (compilation-mode-line-exit :inherit compilation-info)
    (compilation-mode-line-fail :inherit compilation-error)
    (compilation-warning :inherit warning :slant italic)
    (corfu-current :background "#282c34" :foreground "#bbc2cf")
    (corfu-default :inherit tooltip)
    (cperl-array-face :weight bold :inherit font-lock-variable-name-face)
    (cperl-hash-face :weight bold :slant italic :inherit font-lock-variable-name-face)
    (cperl-nonoverridable-face :inherit font-lock-builtin-face)
    (css-property :foreground "#98be65")
    (css-proprietary-property :foreground "#da8548")
    (css-selector :foreground "#51afef")
    (cursor :background "#51afef")
    (custom-button :foreground "#51afef" :background "#282c34" :box (:line-width 1 :style nil))
    (custom-button-mouse :foreground "#282c34" :background "#51afef" :box (:line-width 1 :style nil))
    (custom-button-pressed :foreground "#282c34" :background "#51afef" :box (:line-width 1 :style nil))
    (custom-button-pressed-unraised :foreground "#282c34" :background "#a9a1e1" :box (:line-width 1 :style nil))
    (custom-button-unraised :foreground "#a9a1e1" :background "#282c34" :box (:line-width 1 :style nil))
    (custom-changed :foreground "#51afef" :background "#282c34")
    (custom-comment :foreground "#bbc2cf" :background "#42444a")
    (custom-comment-tag :foreground "#3f444a")
    (custom-group-subtitle :foreground "#ff6c6b")
    (custom-group-tag :foreground "#a9a1e1")
    (custom-group-tag-1 :foreground "#51afef")
    (custom-invalid :foreground "#ff6c6b" :background "#53383f")
    (custom-modified :foreground "#51afef" :background "#304659")
    (custom-saved :foreground "#98be65" :background "#3e493d" :bold t)
    (custom-set :foreground "#ECBE7B" :background "#282c34")
    (custom-state :foreground "#98be65" :background "#3e493d")
    (custom-themed :foreground "#ECBE7B" :background "#282c34")
    (custom-variable-button :foreground "#98be65" :underline t)
    (custom-variable-obsolete :foreground "#3f444a" :background "#282c34")
    (custom-variable-tag :foreground "#c678dd")
    (custom-visibility :foreground "#51afef")
    (default :background "#282c34" :foreground "#bbc2cf")
    (diff-added :inherit hl-line :foreground "#98be65")
    (diff-changed :foreground "#a9a1e1")
    (diff-context :foreground "#a4aab6")
    (diff-file-header :foreground "#51afef")
    (diff-header :foreground "#46D9FF")
    (diff-hl-change :foreground "#da8548" :background "#da8548")
    (diff-hl-delete :foreground "#ff6c6b" :background "#ff6c6b")
    (diff-hl-insert :foreground "#98be65" :background "#98be65")
    (diff-hunk-header :foreground "#a9a1e1")
    (diff-indicator-added :foreground "#98be65")
    (diff-indicator-changed :foreground "#da8548")
    (diff-indicator-removed :foreground "#ff6c6b")
    (diff-refine-added :inherit diff-added :inverse-video t)
    (diff-refine-changed :inherit diff-changed :inverse-video t)
    (diff-refine-removed :inherit diff-removed :inverse-video t)
    (diff-removed :foreground "#ff6c6b" :background "#23272e")
    (dired-directory :foreground "#c678dd")
    (dired-flagged :foreground "#ff6c6b")
    (dired-header :foreground "#51afef" :weight bold)
    (dired-ignored :foreground "#5B6268")
    (dired-k-added :foreground "#98be65" :weight bold)
    (dired-k-commited :foreground "#98be65" :weight bold)
    (dired-k-directory :foreground "#51afef" :weight bold)
    (dired-k-ignored :foreground "#5B6268" :weight bold)
    (dired-k-modified :foreground "#da8548" :weight bold)
    (dired-k-untracked :foreground "#4db5bd" :weight bold)
    (dired-mark :foreground "#da8548" :weight bold)
    (dired-marked :foreground "#c678dd" :weight bold :inverse-video t)
    (dired-perm-write :foreground "#bbc2cf" :underline t)
    (dired-subtree-depth-1-face :background "#20232a")
    (dired-subtree-depth-2-face :background "#1f2229")
    (dired-subtree-depth-3-face :background "#1f2128")
    (dired-subtree-depth-4-face :background "#1e2127")
    (dired-subtree-depth-5-face :background "#1d2026")
    (dired-subtree-depth-6-face :background "#1d1f25")
    (dired-symlink :foreground "#46D9FF" :weight bold)
    (dired-warning :foreground "#ECBE7B")
    (diredfl-autofile-name :foreground "#3f444a")
    (diredfl-compressed-file-name :foreground "#ECBE7B")
    (diredfl-compressed-file-suffix :foreground "#926140")
    (diredfl-date-time :foreground "#46D9FF" :weight light)
    (diredfl-deletion :foreground "#ff6c6b" :background "#53383f" :weight bold)
    (diredfl-deletion-file-name :foreground "#ff6c6b" :background "#53383f")
    (diredfl-dir-heading :foreground "#51afef" :weight bold)
    (diredfl-dir-name :foreground "#51afef")
    (diredfl-dir-priv :foreground "#51afef")
    (diredfl-exec-priv :foreground "#98be65")
    (diredfl-executable-tag :foreground "#98be65")
    (diredfl-file-name :foreground "#bbc2cf")
    (diredfl-file-suffix :foreground "#808591")
    (diredfl-flag-mark :foreground "#ECBE7B" :background "#4f4942" :weight bold)
    (diredfl-flag-mark-line :background "#3b3a3b")
    (diredfl-ignored-file-name :foreground "#5B6268")
    (diredfl-link-priv :foreground "#a9a1e1")
    (diredfl-no-priv :inherit shadow)
    (diredfl-number :foreground "#da8548")
    (diredfl-other-priv :foreground "#c678dd")
    (diredfl-rare-priv :foreground "#bbc2cf")
    (diredfl-read-priv :foreground "#ECBE7B")
    (diredfl-symlink :foreground "#a9a1e1")
    (diredfl-tagged-autofile-name :foreground "#5B6268")
    (diredfl-write-priv :foreground "#ff6c6b")
    (diredp-compressed-file-suffix :foreground "#5B6268")
    (diredp-date-time :foreground "#51afef")
    (diredp-dir-heading :foreground "#51afef" :weight bold)
    (diredp-dir-name :foreground "#DFDFDF" :weight bold)
    (diredp-dir-priv :foreground "#51afef" :weight bold)
    (diredp-exec-priv :foreground "#ECBE7B")
    (diredp-file-name :foreground "#DFDFDF")
    (diredp-file-suffix :foreground "#a9a1e1")
    (diredp-ignored-file-name :foreground "#5B6268")
    (diredp-no-priv :foreground "#5B6268")
    (diredp-number :foreground "#c678dd")
    (diredp-rare-priv :foreground "#ff6c6b" :weight bold)
    (diredp-read-priv :foreground "#c678dd")
    (diredp-symlink :foreground "#a9a1e1")
    (diredp-write-priv :foreground "#98be65")
    (disk-usage-children :foreground "#ECBE7B")
    (disk-usage-percent :foreground "#a9a1e1")
    (disk-usage-size :foreground "#51afef")
    (disk-usage-symlink :foreground "#46D9FF" :weight bold)
    (doom-modeline-bar :background "#51afef")
    (doom-modeline-buffer-file :inherit mode-line-buffer-id :weight bold)
    (doom-modeline-buffer-path :inherit mode-line-emphasis :weight bold)
    (doom-modeline-buffer-project-root :foreground "#98be65" :weight bold)
    (doom-modeline-eldoc-bar :background "#98be65")
    (doom-neotree-data-file-face :foreground "#a9a1e1")
    (doom-neotree-dir-face :foreground "#51afef")
    (doom-neotree-file-face :foreground "#DFDFDF")
    (doom-neotree-hidden-file-face :foreground "#5B6268")
    (doom-neotree-media-file-face :inherit doom-neotree-hidden-file-face)
    (doom-neotree-text-file-face :foreground "#bbc2cf")
    (doom-themes-visual-bell :background "#ff6c6b")
    (ediff-current-diff-A :foreground "#ff6c6b" :background "#4f343a" :extend t)
    (ediff-current-diff-B :foreground "#98be65" :background "#3e493d" :extend t)
    (ediff-current-diff-C :inherit ediff-current-diff-A)
    (ediff-even-diff-A :inherit hl-line)
    (ediff-even-diff-B :inherit ediff-even-diff-A)
    (ediff-even-diff-C :inherit ediff-even-diff-A)
    (ediff-fine-diff-A :inherit diff-refine-removed)
    (ediff-fine-diff-B :inherit diff-refine-added)
    (ediff-fine-diff-C :inherit ediff-fine-diff-A)
    (ediff-odd-diff-A :inherit ediff-even-diff-A)
    (ediff-odd-diff-B :inherit ediff-odd-diff-A)
    (ediff-odd-diff-C :inherit ediff-odd-diff-A)
    (elfeed-log-debug-level-face :foreground "#5B6268")
    (elfeed-log-error-level-face :inherit error)
    (elfeed-log-info-level-face :inherit success)
    (elfeed-log-warn-level-face :inherit warning)
    (elfeed-search-date-face :foreground "#a9a1e1")
    (elfeed-search-feed-face :foreground "#51afef")
    (elfeed-search-filter-face :foreground "#a9a1e1")
    (elfeed-search-tag-face :foreground "#5B6268")
    (elfeed-search-title-face :foreground "#5B6268")
    (elfeed-search-unread-count-face :foreground "#ECBE7B")
    (elfeed-search-unread-title-face :foreground "#bbc2cf" :weight bold)
    (elixir-atom-face :foreground "#2257A0")
    (elixir-attribute-face :foreground "#a9a1e1")
    (elscreen-tab-background-face :background "#282c34")
    (elscreen-tab-control-face :background "#282c34" :foreground "#282c34")
    (elscreen-tab-current-screen-face :background "#21242b" :foreground "#bbc2cf")
    (elscreen-tab-other-screen-face :background "#353a42" :foreground "#1e2022")
    (embark-target :background "#42444a" :extend t)
    (enh-ruby-heredoc-delimiter-face :inherit font-lock-string-face)
    (enh-ruby-op-face :foreground "#51afef")
    (enh-ruby-regexp-delimiter-face :inherit enh-ruby-regexp-face)
    (enh-ruby-regexp-face :foreground "#a9a1e1")
    (enh-ruby-string-delimiter-face :inherit font-lock-string-face)
    (erc-action-face :weight bold)
    (erc-button :weight bold :underline t)
    (erc-command-indicator-face :weight bold)
    (erc-current-nick-face :foreground "#98be65" :weight bold)
    (erc-default-face :inherit default)
    (erc-direct-msg-face :foreground "#c678dd")
    (erc-error-face :inherit error)
    (erc-header-line :background "#1c1e24" :foreground "#51afef")
    (erc-input-face :foreground "#98be65")
    (erc-my-nick-face :foreground "#98be65" :weight bold)
    (erc-my-nick-prefix-face :inherit erc-my-nick-face)
    (erc-nick-default-face :weight bold)
    (erc-nick-msg-face :foreground "#c678dd")
    (erc-nick-prefix-face :inherit erc-nick-default-face)
    (erc-notice-face :foreground "#5B6268")
    (erc-prompt-face :foreground "#51afef" :weight bold)
    (erc-timestamp-face :foreground "#51afef" :weight bold)
    (erm-syn-errline :underline (:style wave :color "#ff6c6b"))
    (erm-syn-warnline :underline (:style wave :color "#ECBE7B"))
    (error :foreground "#ff6c6b")
    (escape-glyph :foreground "#46D9FF")
    (eshell-ls-archive :foreground "#c678dd")
    (eshell-ls-backup :foreground "#ECBE7B")
    (eshell-ls-clutter :foreground "#ff6c6b")
    (eshell-ls-directory :foreground "#51afef")
    (eshell-ls-executable :foreground "#98be65")
    (eshell-ls-missing :foreground "#ff6c6b")
    (eshell-ls-product :foreground "#da8548")
    (eshell-ls-readonly :foreground "#da8548")
    (eshell-ls-special :foreground "#a9a1e1")
    (eshell-ls-symlink :foreground "#46D9FF")
    (eshell-ls-unreadable :foreground "#5B6268")
    (eshell-prompt :foreground "#51afef" :weight bold)
    (evil-ex-info :foreground "#ff6c6b" :slant italic)
    (evil-ex-search :background "#51afef" :foreground "#1B2229" :weight bold)
    (evil-ex-substitute-matches :background "#1B2229" :foreground "#ff6c6b" :weight bold :strike-through t)
    (evil-ex-substitute-replacement :background "#1B2229" :foreground "#98be65" :weight bold)
    (evil-goggles-default-face :inherit region :background "#35383f")
    (evil-mc-cursor-bar-face :height 1 :background "#c678dd" :foreground "#1B2229")
    (evil-mc-cursor-default-face :background "#c678dd" :foreground "#1B2229")
    (evil-mc-cursor-hbar-face :underline (:color "#51afef"))
    (evil-mc-region-face :inherit region)
    (evil-search-highlight-persist-highlight-face :inherit lazy-highlight)
    (evil-snipe-first-match-face :foreground "#51afef" :background "#2257A0" :weight bold)
    (evil-snipe-matches-face :foreground "#51afef" :underline t :weight bold)
    (eww-form-checkbox :inherit eww-form-file)
    (eww-form-file :inherit eww-form-submit :background "#21242b")
    (eww-form-select :inherit eww-form-submit :background "#21242b")
    (eww-form-submit :inherit eww-form-text :box (:line-width 2 :style released-button) :background "#202328")
    (eww-form-text :box (:line-width 1 :color "#23272e") :background "#282c34" :foreground "#bbc2cf" :distant-foreground "#282c34")
    (eww-form-textarea :inherit eww-form-text)
    (eww-invalid-certificate :foreground "#ff6c6b")
    (eww-valid-certificate :foreground "#51afef")
    (eyebrowse-mode-line-active :weight bold :foreground "#51afef")
    (flx-highlight-face :weight bold :foreground "#ECBE7B" :underline unspecified)
    (flycheck-error :underline (:style wave :color "#ff6c6b"))
    (flycheck-fringe-error :inherit fringe :foreground "#ff6c6b")
    (flycheck-fringe-info :inherit fringe :foreground "#98be65")
    (flycheck-fringe-warning :inherit fringe :foreground "#ECBE7B")
    (flycheck-info :underline (:style wave :color "#98be65"))
    (flycheck-posframe-background-face :background "#21242b")
    (flycheck-posframe-error-face :inherit flycheck-posframe-face :foreground "#ff6c6b")
    (flycheck-posframe-face :inherit default)
    (flycheck-posframe-info-face :inherit flycheck-posframe-face :foreground "#98be65")
    (flycheck-posframe-warning-face :inherit flycheck-posframe-face :foreground "#ECBE7B")
    (flycheck-warning :underline (:style wave :color "#ECBE7B"))
    (flymake-error :underline (:style wave :color "#ff6c6b"))
    (flymake-note :underline (:style wave :color "#98be65"))
    (flymake-warning :underline (:style wave :color "#da8548"))
    (flyspell-duplicate :underline (:style wave :color "#ECBE7B"))
    (flyspell-incorrect :underline (:style wave :color "#ff6c6b"))
    (font-latex-bold-face :inherit bold)
    (font-latex-italic-face :inherit italic)
    (font-latex-math-face :foreground "#98be65")
    (font-latex-script-char-face :foreground "#2257A0")
    (font-latex-sectioning-0-face :foreground "#51afef" :weight ultra-bold)
    (font-latex-sectioning-1-face :foreground "#c678dd" :weight semi-bold)
    (font-latex-sectioning-2-face :foreground "#a9a1e1" :weight semi-bold)
    (font-latex-sectioning-3-face :foreground "#85c7f3" :weight semi-bold)
    (font-latex-sectioning-4-face :foreground "#d7a0e7" :weight semi-bold)
    (font-latex-sectioning-5-face :foreground "#c2bdea" :weight semi-bold)
    (font-latex-sedate-face :inherit font-lock-keyword-face)
    (font-latex-string-face :inherit font-lock-string-face)
    (font-latex-underline-face :inherit underline)
    (font-latex-verbatim-face :inherit fixed-pitch :foreground "#a9a1e1" :slant italic)
    (font-latex-warning-face :inherit font-lock-warning-face)
    (font-lock-bracket-face :inherit font-lock-punctuation-face)
    (font-lock-builtin-face :foreground "#c678dd")
    (font-lock-comment-delimiter-face :inherit font-lock-comment-face)
    (font-lock-comment-face :foreground "#5B6268" :background unspecified)
    (font-lock-constant-face :foreground "#a9a1e1")
    (font-lock-delimiter-face :inherit font-lock-punctuation-face)
    (font-lock-doc-face :inherit font-lock-comment-face :foreground "#83898d")
    (font-lock-escape-face :inherit font-lock-regexp-grouping-backslash)
    (font-lock-function-call-face :inherit font-lock-function-name-face :slant italic :foreground "#c28ed8")
    (font-lock-function-name-face :foreground "#c678dd")
    (font-lock-keyword-face :foreground "#51afef")
    (font-lock-misc-punctuation-face :inherit font-lock-punctuation-face)
    (font-lock-negation-char-face :inherit bold :foreground "#51afef")
    (font-lock-number-face :foreground "#da8548")
    (font-lock-operator-face :foreground "#51afef")
    (font-lock-preprocessor-char-face :inherit bold :foreground "#51afef")
    (font-lock-preprocessor-face :inherit bold :foreground "#51afef")
    (font-lock-property-name-face :foreground "#7bb6e2" :weight bold)
    (font-lock-property-use-face :inherit font-lock-property-name-face :weight regular)
    (font-lock-punctuation-face :foreground "#a0bdd7")
    (font-lock-regexp-grouping-backslash :inherit bold :foreground "#51afef")
    (font-lock-regexp-grouping-construct :inherit bold :foreground "#51afef")
    (font-lock-string-face :foreground "#98be65")
    (font-lock-type-face :foreground "#ECBE7B")
    (font-lock-variable-name-face :foreground "#dcaeea")
    (font-lock-variable-use-face :inherit font-lock-variable-name-face :foreground "#cbb8dc")
    (font-lock-warning-face :inherit warning)
    (forge-dimmed :inherit magit-dimmed)
    (forge-pullreq-merged :inherit forge-issue-completed)
    (forge-pullreq-open :inherit forge-issue-open)
    (forge-pullreq-rejected :inherit forge-issue-unplanned)
    (fringe :inherit default :foreground "#3f444a")
    (git-commit-comment-branch-local :foreground "#c678dd")
    (git-commit-comment-branch-remote :foreground "#98be65")
    (git-commit-comment-detached :foreground "#da8548")
    (git-commit-comment-file :foreground "#a9a1e1")
    (git-commit-comment-heading :foreground "#51afef")
    (git-commit-keyword :foreground "#46D9FF" :slant italic)
    (git-commit-known-pseudo-header :foreground "#83898d" :weight bold :slant italic)
    (git-commit-nonempty-second-line :inherit git-commit-overlong-summary)
    (git-commit-overlong-summary :inherit error :background "#1B2229" :slant italic :weight bold)
    (git-commit-pseudo-header :foreground "#83898d" :slant italic)
    (git-commit-summary :foreground "#98be65")
    (git-gutter+-added :inherit fringe :foreground "#98be65" :background unspecified)
    (git-gutter+-deleted :inherit fringe :foreground "#ff6c6b" :background unspecified)
    (git-gutter+-modified :inherit fringe :foreground "#da8548" :background unspecified)
    (git-gutter-fr:added :inherit fringe :foreground "#98be65")
    (git-gutter-fr:deleted :inherit fringe :foreground "#ff6c6b")
    (git-gutter-fr:modified :inherit fringe :foreground "#da8548")
    (git-gutter:added :inherit fringe :foreground "#98be65")
    (git-gutter:deleted :inherit fringe :foreground "#ff6c6b")
    (git-gutter:modified :inherit fringe :foreground "#da8548")
    (gnus-cite-1 :foreground "#a9a1e1")
    (gnus-cite-10 :foreground "#ECBE7B")
    (gnus-cite-11 :foreground "#ECBE7B")
    (gnus-cite-2 :foreground "#ECBE7B")
    (gnus-cite-3 :foreground "#c678dd")
    (gnus-cite-4 :foreground "#98be65")
    (gnus-cite-5 :foreground "#98be65")
    (gnus-cite-6 :foreground "#98be65")
    (gnus-cite-7 :foreground "#c678dd")
    (gnus-cite-8 :foreground "#c678dd")
    (gnus-cite-9 :foreground "#c678dd")
    (gnus-group-mail-1 :weight bold :foreground "#bbc2cf")
    (gnus-group-mail-1-empty :foreground "#5B6268")
    (gnus-group-mail-2 :inherit gnus-group-mail-1)
    (gnus-group-mail-2-empty :inherit gnus-group-mail-1-empty)
    (gnus-group-mail-3 :inherit gnus-group-mail-1)
    (gnus-group-mail-3-empty :inherit gnus-group-mail-1-empty)
    (gnus-group-mail-low :inherit gnus-group-mail-1 :weight normal)
    (gnus-group-mail-low-empty :inherit gnus-group-mail-1-empty)
    (gnus-group-news-1 :inherit gnus-group-mail-1)
    (gnus-group-news-1-empty :inherit gnus-group-mail-1-empty)
    (gnus-group-news-2 :inherit gnus-group-news-1)
    (gnus-group-news-2-empty :inherit gnus-group-news-1-empty)
    (gnus-group-news-3 :inherit gnus-group-news-1)
    (gnus-group-news-3-empty :inherit gnus-group-news-1-empty)
    (gnus-group-news-4 :inherit gnus-group-news-1)
    (gnus-group-news-4-empty :inherit gnus-group-news-1-empty)
    (gnus-group-news-5 :inherit gnus-group-news-1)
    (gnus-group-news-5-empty :inherit gnus-group-news-1-empty)
    (gnus-group-news-6 :inherit gnus-group-news-1)
    (gnus-group-news-6-empty :inherit gnus-group-news-1-empty)
    (gnus-group-news-low :inherit gnus-group-mail-1 :foreground "#5B6268")
    (gnus-group-news-low-empty :inherit gnus-group-news-low :weight normal)
    (gnus-header-content :inherit message-header-other)
    (gnus-header-from :inherit message-header-other)
    (gnus-header-name :inherit message-header-name)
    (gnus-header-newsgroups :inherit message-header-other)
    (gnus-header-subject :inherit message-header-subject)
    (gnus-signature :foreground "#ECBE7B")
    (gnus-summary-cancelled :foreground "#ff6c6b" :strike-through t)
    (gnus-summary-high-ancient :foreground "#7b8186" :inherit italic)
    (gnus-summary-high-read :foreground "#c8ced8")
    (gnus-summary-high-ticked :foreground "#d193e3")
    (gnus-summary-high-unread :foreground "#accb83")
    (gnus-summary-low-ancient :foreground "#484e53" :inherit italic)
    (gnus-summary-low-read :foreground "#959ba5")
    (gnus-summary-low-ticked :foreground "#9e60b0")
    (gnus-summary-low-unread :foreground "#799850")
    (gnus-summary-normal-ancient :foreground "#5B6268" :inherit italic)
    (gnus-summary-normal-read :foreground "#bbc2cf")
    (gnus-summary-normal-ticked :foreground "#c678dd")
    (gnus-summary-normal-unread :foreground "#98be65" :inherit bold)
    (gnus-summary-selected :foreground "#51afef" :weight bold)
    (gnus-x-face :background "#5B6268" :foreground "#bbc2cf")
    (goggles-added :background "#3e4a39")
    (goggles-changed :inherit region)
    (goggles-removed :background "#58363b" :extend t)
    (header-line :inherit mode-line)
    (header-line-highlight :inherit mode-line-highlight)
    (helm-ff-directory :foreground "#dcaeea")
    (helm-ff-dotted-directory :foreground "#3f444a")
    (helm-ff-executable :foreground "#DFDFDF" :inherit italic)
    (helm-ff-file :foreground "#bbc2cf")
    (helm-ff-prefix :foreground "#51afef")
    (helm-grep-file :foreground "#46D9FF")
    (helm-grep-finish :foreground "#98be65")
    (helm-grep-lineno :foreground "#5B6268")
    (helm-grep-match :foreground "#51afef" :distant-foreground "#ff6c6b")
    (helm-match :inherit bold :foreground "#51afef" :distant-foreground "#DFDFDF")
    (helm-moccur-buffer :inherit link)
    (helm-rg-active-arg-face :foreground "#98be65" :weight normal)
    (helm-rg-base-rg-cmd-face :foreground "#3f444a" :weight normal)
    (helm-rg-colon-separator-ripgrep-output-face :foreground "#DFDFDF")
    (helm-rg-directory-cmd-face :foreground "#b18e5c" :background "#1B2229" :weight normal)
    (helm-rg-directory-header-face :foreground "#DFDFDF" :background "#1B2229" :weight bold)
    (helm-rg-error-message :foreground "#ff6c6b")
    (helm-rg-extra-arg-face :foreground "#ECBE7B" :weight normal)
    (helm-rg-file-match-face :foreground "#46D9FF" :underline t)
    (helm-rg-inactive-arg-face :foreground "#3f444a" :weight normal)
    (helm-rg-line-number-match-face :foreground "#da8548" :underline t)
    (helm-rg-match-text-face :foreground "#DFDFDF" :background "#a9a1e1")
    (helm-rg-title-face :foreground "#a9a1e1" :background "#1B2229" :weight bold)
    (helm-selection :inherit bold :background "#2257A0" :extend t :distant-foreground "#51afef")
    (helm-source-header :background "#202328" :foreground "#51afef" :weight bold)
    (helm-swoop-target-line-block-face :foreground "#ECBE7B")
    (helm-swoop-target-line-face :foreground "#51afef" :inverse-video t)
    (helm-swoop-target-number-face :foreground "#5B6268")
    (helm-swoop-target-word-face :foreground "#98be65" :inherit bold)
    (helm-visible-mark :inherit (bold highlight))
    (helpful-heading :weight bold :height 1.2)
    (hi-blue :background "#51afef")
    (hi-blue-b :foreground "#51afef" :weight bold)
    (hi-green :background "#98be65")
    (hi-green-b :foreground "#98be65" :weight bold)
    (hi-pink :background "#c678dd")
    (hi-red-b :foreground "#ff6c6b" :weight bold)
    (hi-yellow :background "#ECBE7B")
    (highlight :background "#51afef" :foreground "#1B2229" :distant-foreground "#DFDFDF")
    (highlight-indentation-current-column-face :background "#1c1f24")
    (highlight-indentation-face :inherit hl-line)
    (highlight-indentation-guides-even-face :inherit highlight-indentation-face)
    (highlight-indentation-guides-odd-face :inherit highlight-indentation-face)
    (highlight-numbers-number :inherit bold :foreground "#da8548")
    (highlight-quoted-quote :foreground "#51afef")
    (highlight-quoted-symbol :foreground "#ECBE7B")
    (highlight-symbol-face :background "#54565c" :distant-foreground "#5B6268")
    (highlight-thing :background "#54565c" :distant-foreground "#5B6268")
    (hl-fill-column-face :inherit (hl-line shadow))
    (hl-line :background "#21242b" :extend t)
    (hl-todo :foreground "#ff6c6b" :weight bold)
    (hydra-face-amaranth :foreground "#c678dd" :weight bold)
    (hydra-face-blue :foreground "#51afef" :weight bold)
    (hydra-face-pink :foreground "#a9a1e1" :weight bold)
    (hydra-face-red :foreground "#ff6c6b" :weight bold)
    (hydra-face-teal :foreground "#4db5bd" :weight bold)
    (ido-first-match :foreground "#da8548")
    (ido-indicator :foreground "#ff6c6b" :background "#282c34")
    (ido-only-match :foreground "#98be65")
    (ido-subdir :foreground "#a9a1e1")
    (ido-virtual :foreground "#5B6268")
    (iedit-occurrence :foreground "#c678dd" :weight bold :inverse-video t)
    (iedit-read-only-occurrence :inherit region)
    (imenu-list-entry-face-0 :foreground "#51afef")
    (imenu-list-entry-face-1 :foreground "#98be65")
    (imenu-list-entry-face-2 :foreground "#ECBE7B")
    (imenu-list-entry-subalist-face-0 :inherit imenu-list-entry-face-0 :weight bold)
    (imenu-list-entry-subalist-face-1 :inherit imenu-list-entry-face-1 :weight bold)
    (imenu-list-entry-subalist-face-2 :inherit imenu-list-entry-face-2 :weight bold)
    (indent-guide-face :inherit hl-line)
    (isearch :inherit lazy-highlight :weight bold)
    (isearch-fail :background "#ff6c6b" :foreground "#1B2229" :weight bold)
    (italic :slant italic)
    (ivy-confirm-face :foreground "#98be65")
    (ivy-current-match :background "#2257A0" :distant-foreground "#1B2229" :weight normal)
    (ivy-highlight-face :foreground "#a9a1e1")
    (ivy-match-required-face :foreground "#ff6c6b")
    (ivy-minibuffer-match-face-1 :foreground "#595e63" :weight light)
    (ivy-minibuffer-match-face-2 :inherit ivy-minibuffer-match-face-1 :foreground "#c678dd" :background "#1c1f24" :weight semi-bold)
    (ivy-minibuffer-match-face-3 :inherit ivy-minibuffer-match-face-2 :foreground "#98be65" :weight semi-bold)
    (ivy-minibuffer-match-face-4 :inherit ivy-minibuffer-match-face-2 :foreground "#ECBE7B" :weight semi-bold)
    (ivy-minibuffer-match-highlight :foreground "#a9a1e1")
    (ivy-modified-buffer :inherit bold :foreground "#ECBE7B")
    (ivy-posframe :background "#1a1c22")
    (ivy-posframe-border :inherit internal-border)
    (ivy-virtual :inherit italic :foreground "#83898d")
    (jabber-activity-face :foreground "#ff6c6b" :weight bold)
    (jabber-activity-personal-face :foreground "#51afef" :weight bold)
    (jabber-chat-error :foreground "#ff6c6b" :weight bold)
    (jabber-chat-prompt-foreign :foreground "#ff6c6b" :weight bold)
    (jabber-chat-prompt-local :foreground "#51afef" :weight bold)
    (jabber-chat-prompt-system :foreground "#98be65" :weight bold)
    (jabber-chat-text-foreign :foreground "#bbc2cf")
    (jabber-chat-text-local :foreground "#bbc2cf")
    (jabber-rare-time-face :foreground "#98be65")
    (jabber-roster-user-away :foreground "#ECBE7B")
    (jabber-roster-user-chatty :foreground "#98be65" :weight bold)
    (jabber-roster-user-dnd :foreground "#ff6c6b")
    (jabber-roster-user-error :foreground "#ff6c6b")
    (jabber-roster-user-offline :foreground "#bbc2cf")
    (jabber-roster-user-online :foreground "#98be65" :weight bold)
    (jabber-roster-user-xa :foreground "#46D9FF")
    (jdee-font-lock-bold-face :inherit bold)
    (jdee-font-lock-constant-face :inherit font-lock-constant-face)
    (jdee-font-lock-constructor-face :foreground "#46D9FF")
    (jdee-font-lock-doc-tag-face :foreground "#a9a1e1")
    (jdee-font-lock-italic-face :inherit italic)
    (jdee-font-lock-link-face :foreground "#51afef" :slant unspecified :underline t)
    (jdee-font-lock-modifier-face :inherit font-lock-type-face)
    (jdee-font-lock-number-face :foreground "#da8548")
    (jdee-font-lock-operator-face :foreground "#51afef")
    (jdee-font-lock-private-face :inherit font-lock-keyword-face)
    (jdee-font-lock-protected-face :inherit font-lock-keyword-face)
    (jdee-font-lock-public-face :inherit font-lock-keyword-face)
    (js2-external-variable :foreground "#51afef")
    (js2-function-call :foreground "#c678dd")
    (js2-function-param :foreground "#dcaeea")
    (js2-jsdoc-tag :foreground "#83898d")
    (js2-object-property :foreground "#a9a1e1")
    (keycast-command :inherit mode-line-emphasis)
    (keycast-key :inherit (bold mode-line-highlight))
    (lazy-highlight :background "#387aa7" :foreground "#DFDFDF" :distant-foreground "#1B2229" :weight bold)
    (ledger-font-payee-cleared-face :foreground "#a9a1e1" :weight bold)
    (ledger-font-payee-uncleared-face :foreground "#5B6268" :weight bold)
    (ledger-font-posting-account-face :foreground "#DFDFDF")
    (ledger-font-posting-amount-face :foreground "#ECBE7B")
    (ledger-font-posting-date-face :foreground "#51afef")
    (ledger-font-xact-highlight-face :background "#1B2229")
    (line-number :inherit default :foreground "#3f444a" :distant-foreground unspecified :weight normal :slant unspecified :underline unspecified :strike-through unspecified)
    (line-number-current-line :inherit (hl-line default) :foreground "#bbc2cf" :distant-foreground unspecified :weight normal :slant unspecified :underline unspecified :strike-through unspecified)
    (link :foreground "#51afef" :underline t :weight bold)
    (linum :inherit default :foreground "#3f444a" :distant-foreground unspecified :weight normal :slant unspecified :underline unspecified :strike-through unspecified)
    (linum-highlight-face :foreground "#bbc2cf" :weight normal)
    (linum-relative-current-face :inherit (hl-line default) :foreground "#bbc2cf" :distant-foreground unspecified :weight normal :slant unspecified :underline unspecified :strike-through unspecified)
    (lsp-face-highlight-read :inherit lsp-face-highlight-textual)
    (lsp-face-highlight-textual :weight bold :background "#23272e" :foreground "#1B2229" :distant-foreground "#DFDFDF")
    (lsp-face-highlight-write :inherit lsp-face-highlight-textual)
    (lsp-headerline-breadcrumb-separator-face :inherit shadow)
    (lsp-ui-doc-background :inherit tooltip)
    (lsp-ui-peek-filename :inherit mode-line-buffer-id)
    (lsp-ui-peek-header :foreground "#bbc2cf" :background "#3d4148" :bold t)
    (lsp-ui-peek-highlight :inherit isearch :box t)
    (lsp-ui-peek-line-number :foreground "#98be65")
    (lsp-ui-peek-list :background "#24272e")
    (lsp-ui-peek-peek :background "#24272e")
    (lsp-ui-peek-selection :foreground "#282c34" :background "#51afef" :bold t)
    (lsp-ui-sideline-code-action :foreground "#4a9bd2")
    (lsp-ui-sideline-current-symbol :inherit highlight)
    (lsp-ui-sideline-symbol-info :foreground "#535960" :background "#21242b" :extend t)
    (lui-button-face :foreground "#c678dd" :underline t)
    (lui-highlight-face :foreground "#51afef")
    (lui-time-stamp-face :foreground "#a9a1e1")
    (magit-bisect-bad :foreground "#ff6c6b")
    (magit-bisect-good :foreground "#98be65")
    (magit-bisect-skip :foreground "#da8548")
    (magit-blame-date :foreground "#ff6c6b")
    (magit-blame-hash :foreground "#46D9FF")
    (magit-blame-heading :foreground "#da8548" :background "#23272e" :extend t)
    (magit-branch-current :foreground "#51afef")
    (magit-branch-local :foreground "#46D9FF")
    (magit-branch-remote :foreground "#98be65")
    (magit-cherry-equivalent :foreground "#a9a1e1")
    (magit-cherry-unmatched :foreground "#46D9FF")
    (magit-diff-added :foreground "#799850" :background "#333a38" :extend t)
    (magit-diff-added-highlight :foreground "#98be65" :background "#3e493d" :weight bold :extend t)
    (magit-diff-base :foreground "#ae6a39" :background "#393436" :extend t)
    (magit-diff-base-highlight :foreground "#da8548" :background "#4b3d38" :weight bold :extend t)
    (magit-diff-context :foreground "#70747c" :background "#282c34" :extend t)
    (magit-diff-context-highlight :foreground "#bbc2cf" :background "#21242b" :extend t)
    (magit-diff-file-heading :foreground "#bbc2cf" :weight bold :extend t)
    (magit-diff-file-heading-selection :foreground "#c678dd" :background "#2257A0" :weight bold :extend t)
    (magit-diff-hunk-heading :foreground "#282c34" :background "#4e4f67" :extend t)
    (magit-diff-hunk-heading-highlight :foreground "#282c34" :background "#a9a1e1" :weight bold :extend t)
    (magit-diff-lines-heading :foreground "#ECBE7B" :background "#ff6c6b" :extend t :extend t)
    (magit-diff-removed :foreground "#cc5655" :background "#392d34" :extend t)
    (magit-diff-removed-highlight :foreground "#ff6c6b" :background "#4f343a" :weight bold :extend t)
    (magit-diffstat-added :foreground "#98be65")
    (magit-diffstat-removed :foreground "#ff6c6b")
    (magit-dimmed :foreground "#5B6268")
    (magit-filename :foreground "#a9a1e1")
    (magit-hash :foreground "#5B6268")
    (magit-header-line :background "#2257A0" :foreground "#DFDFDF" :weight bold :box (:line-width 3 :color "#2257A0"))
    (magit-log-author :foreground "#da8548")
    (magit-log-date :foreground "#51afef")
    (magit-log-graph :foreground "#5B6268")
    (magit-process-ng :inherit error)
    (magit-process-ok :inherit success)
    (magit-reflog-amend :foreground "#c678dd")
    (magit-reflog-checkout :foreground "#51afef")
    (magit-reflog-cherry-pick :foreground "#98be65")
    (magit-reflog-commit :foreground "#98be65")
    (magit-reflog-merge :foreground "#98be65")
    (magit-reflog-other :foreground "#46D9FF")
    (magit-reflog-rebase :foreground "#c678dd")
    (magit-reflog-remote :foreground "#46D9FF")
    (magit-reflog-reset :inherit error)
    (magit-refname :foreground "#5B6268")
    (magit-section-heading :foreground "#51afef" :weight bold :extend t)
    (magit-section-heading-selection :foreground "#da8548" :weight bold :extend t)
    (magit-section-highlight :inherit hl-line)
    (magit-section-secondary-heading :foreground "#a9a1e1" :weight bold :extend t)
    (magit-sequence-drop :foreground "#ff6c6b")
    (magit-sequence-head :foreground "#51afef")
    (magit-sequence-part :foreground "#da8548")
    (magit-sequence-stop :foreground "#98be65")
    (magit-signature-bad :inherit error)
    (magit-signature-error :inherit error)
    (magit-signature-expired :foreground "#da8548")
    (magit-signature-good :inherit success)
    (magit-signature-revoked :foreground "#c678dd")
    (magit-signature-untrusted :foreground "#ECBE7B")
    (magit-tag :foreground "#ECBE7B")
    (makefile-targets :foreground "#51afef")
    (marginalia-documentation :inherit font-lock-doc-face)
    (marginalia-file-priv-dir :foreground "#51afef")
    (marginalia-file-priv-exec :foreground "#98be65")
    (marginalia-file-priv-link :foreground "#a9a1e1")
    (marginalia-file-priv-other :foreground "#c678dd")
    (marginalia-file-priv-rare :foreground "#bbc2cf")
    (marginalia-file-priv-read :foreground "#ECBE7B")
    (marginalia-file-priv-write :foreground "#ff6c6b")
    (marginalia-lighter :foreground "#a9a1e1")
    (marginalia-number :foreground "#da8548")
    (marginalia-size :foreground "#a9a1e1")
    (markdown-blockquote-face :inherit italic :foreground "#83898d")
    (markdown-bold-face :inherit bold :foreground "#da8548")
    (markdown-code-face :background "#2e3138" :extend t)
    (markdown-header-delimiter-face :inherit markdown-header-face)
    (markdown-header-face :inherit bold :foreground "#ff6c6b")
    (markdown-html-attr-name-face :inherit font-lock-variable-name-face)
    (markdown-html-attr-value-face :inherit font-lock-string-face)
    (markdown-html-entity-face :inherit font-lock-variable-name-face)
    (markdown-html-tag-delimiter-face :inherit markdown-markup-face)
    (markdown-html-tag-name-face :inherit font-lock-keyword-face)
    (markdown-inline-code-face :inherit (markdown-code-face markdown-pre-face) :extend unspecified)
    (markdown-italic-face :inherit italic :foreground "#a9a1e1")
    (markdown-link-face :foreground "#51afef")
    (markdown-list-face :foreground "#ff6c6b")
    (markdown-markup-face :foreground "#5B6268")
    (markdown-metadata-key-face :foreground "#ff6c6b")
    (markdown-pre-face :foreground "#98be65")
    (markdown-reference-face :foreground "#83898d")
    (markdown-url-face :foreground "#c678dd" :weight normal)
    (match :foreground "#98be65" :background "#1B2229" :weight bold)
    (mc/cursor-face :inherit cursor)
    (message-cited-text :foreground "#a9a1e1")
    (message-cited-text-1 :foreground "#ECBE7B")
    (message-cited-text-2 :foreground "#c678dd")
    (message-cited-text-3 :foreground "#98be65")
    (message-cited-text-4 :foreground "#98be65")
    (message-header-cc :inherit message-header-to :foreground "#4494cb")
    (message-header-name :foreground "#98be65")
    (message-header-newsgroups :foreground "#ECBE7B")
    (message-header-other :foreground "#a9a1e1")
    (message-header-subject :foreground "#51afef" :weight bold)
    (message-header-to :foreground "#51afef" :weight bold)
    (message-header-xheader :foreground "#83898d")
    (message-mml :foreground "#5B6268" :slant italic)
    (message-separator :foreground "#5B6268")
    (minibuffer-prompt :foreground "#51afef")
    (minimap-active-region-background :background "#191b20")
    (minimap-current-line-face :background "#2257A0")
    (mm-uu-extract :background "#232c35" :foreground "#abbfd3")
    (mmm-cleanup-submode-face :background "#3b3a3b")
    (mmm-code-submode-face :background "#21242b")
    (mmm-comment-submode-face :background "#2c3946")
    (mmm-declaration-submode-face :background "#2b3d48")
    (mmm-init-submode-face :background "#3d3239")
    (mmm-output-submode-face :background "#343745")
    (mmm-special-submode-face :background "#333a38")
    (mode-line :background "#1d2026" :foreground "#bbc2cf" :box unspecified)
    (mode-line-active :inherit mode-line)
    (mode-line-buffer-id :weight bold)
    (mode-line-emphasis :foreground "#51afef")
    (mode-line-highlight :inherit highlight :distant-foreground "#282c34")
    (mode-line-inactive :background "#21242b" :foreground "#5B6268" :box unspecified)
    (nav-flash-face :background "#2257A0" :foreground "#DFDFDF" :weight bold)
    (neo-dir-link-face :foreground "#51afef")
    (neo-expand-btn-face :foreground "#51afef")
    (neo-file-link-face :foreground "#bbc2cf")
    (neo-root-dir-face :foreground "#98be65" :background "#282c34" :box (:line-width 4 :color "#282c34"))
    (neo-vc-added-face :foreground "#98be65")
    (neo-vc-conflict-face :foreground "#c678dd" :weight bold)
    (neo-vc-edited-face :foreground "#ECBE7B")
    (neo-vc-ignored-face :foreground "#5B6268")
    (neo-vc-removed-face :foreground "#ff6c6b" :strike-through t)
    (nerd-icons-blue :foreground "#51afef")
    (nerd-icons-blue-alt :foreground "#4db5bd")
    (nerd-icons-completion-dir-face :foreground "#83898d")
    (nerd-icons-cyan :foreground "#46D9FF")
    (nerd-icons-cyan-alt :foreground "#46D9FF")
    (nerd-icons-dblue :foreground "#2257A0")
    (nerd-icons-dcyan :foreground "#5699AF")
    (nerd-icons-dgreen :foreground "#6a8546")
    (nerd-icons-dired-dir-face :foreground "#83898d")
    (nerd-icons-dmaroon :foreground "#8a549a")
    (nerd-icons-dorange :foreground "#985d32")
    (nerd-icons-dpink :foreground "#ff8281")
    (nerd-icons-dpurple :foreground "#76709d")
    (nerd-icons-dred :foreground "#b24b4a")
    (nerd-icons-dsilver :foreground "#52565c")
    (nerd-icons-dyellow :foreground "#a58556")
    (nerd-icons-green :foreground "#98be65")
    (nerd-icons-lblue :foreground "#85c7f3")
    (nerd-icons-lcyan :foreground "#7de4ff")
    (nerd-icons-lgreen :foreground "#b6d193")
    (nerd-icons-lmaroon :foreground "#d7a0e7")
    (nerd-icons-lorange :foreground "#e5a97e")
    (nerd-icons-lpink :foreground "#ffbcbc")
    (nerd-icons-lpurple :foreground "#c2bdea")
    (nerd-icons-lred :foreground "#ff9897")
    (nerd-icons-lsilver :foreground "#c5c6c8")
    (nerd-icons-lyellow :foreground "#f1d1a2")
    (nerd-icons-maroon :foreground "#c678dd")
    (nerd-icons-orange :foreground "#da8548")
    (nerd-icons-pink :foreground "#ff9f9e")
    (nerd-icons-purple :foreground "#a9a1e1")
    (nerd-icons-purple-alt :foreground "#4e5160")
    (nerd-icons-red :foreground "#ff6c6b")
    (nerd-icons-red-alt :foreground "#5b494e")
    (nerd-icons-silver :foreground "#95989b")
    (nerd-icons-yellow :foreground "#ECBE7B")
    (nlinum-current-line :inherit (hl-line default) :foreground "#bbc2cf" :distant-foreground unspecified :weight normal :slant unspecified :underline unspecified :strike-through unspecified)
    (nlinum-hl-face :inherit (hl-line default) :foreground "#bbc2cf" :distant-foreground unspecified :weight normal :slant unspecified :underline unspecified :strike-through unspecified)
    (nlinum-relative-current-face :inherit (hl-line default) :foreground "#bbc2cf" :distant-foreground unspecified :weight normal :slant unspecified :underline unspecified :strike-through unspecified)
    (nobreak-space :inherit escape-glyph :underline t)
    (notmuch-message-summary-face :foreground "#3f444a")
    (notmuch-search-count :foreground "#5B6268")
    (notmuch-search-date :foreground "#da8548")
    (notmuch-search-flagged-face :foreground "#9f585a")
    (notmuch-search-matching-authors :foreground "#51afef")
    (notmuch-search-non-matching-authors :foreground "#bbc2cf")
    (notmuch-search-subject :foreground "#bbc2cf")
    (notmuch-search-unread-face :weight bold)
    (notmuch-tag-added :foreground "#98be65" :weight normal)
    (notmuch-tag-deleted :foreground "#ff6c6b" :weight normal)
    (notmuch-tag-face :foreground "#ECBE7B" :weight normal)
    (notmuch-tag-flagged :foreground "#ECBE7B" :weight normal)
    (notmuch-tag-unread :foreground "#ECBE7B" :weight normal)
    (notmuch-tree-match-author-face :foreground "#51afef" :weight bold)
    (notmuch-tree-match-date-face :foreground "#da8548" :weight bold)
    (notmuch-tree-match-face :foreground "#bbc2cf")
    (notmuch-tree-match-subject-face :foreground "#bbc2cf")
    (notmuch-tree-match-tag-face :foreground "#ECBE7B")
    (notmuch-tree-match-tree-face :foreground "#5B6268")
    (notmuch-tree-no-match-author-face :foreground "#51afef")
    (notmuch-tree-no-match-date-face :foreground "#da8548")
    (notmuch-tree-no-match-face :foreground "#5B6268")
    (notmuch-tree-no-match-subject-face :foreground "#5B6268")
    (notmuch-tree-no-match-tag-face :foreground "#ECBE7B")
    (notmuch-tree-no-match-tree-face :foreground "#ECBE7B")
    (notmuch-wash-cited-text :foreground "#3f444a")
    (notmuch-wash-toggle-button :foreground "#bbc2cf")
    (objed-hl :inherit region :background "#35383f")
    (objed-mode-line :inherit warning :weight bold)
    (orderless-match-face-0 :weight bold :foreground "#7bb6e2" :background "#2c3946")
    (orderless-match-face-1 :weight bold :foreground "#c195d7" :background "#373344")
    (orderless-match-face-2 :weight bold :foreground "#a5bf8f" :background "#333a38")
    (orderless-match-face-3 :weight bold :foreground "#d8bf9c" :background "#3b3a3b")
    (org-agenda-clocking :background "#304659")
    (org-agenda-date :foreground "#a9a1e1" :weight ultra-bold)
    (org-agenda-date-today :foreground "#cbc6ed" :weight ultra-bold)
    (org-agenda-date-weekend :foreground "#656087" :weight ultra-bold)
    (org-agenda-dimmed-todo-face :foreground "#5B6268")
    (org-agenda-done :inherit org-done)
    (org-agenda-structure :foreground "#bbc2cf" :weight ultra-bold)
    (org-archived :foreground "#83898d")
    (org-block :background "#23272e" :extend t)
    (org-block-background :background "#23272e" :extend t)
    (org-block-begin-line :inherit org-block :foreground "#5B6268")
    (org-block-end-line :inherit org-block-begin-line)
    (org-checkbox :inherit org-todo)
    (org-checkbox-statistics-done :inherit org-done)
    (org-checkbox-statistics-todo :inherit org-todo)
    (org-cite :foreground "#57b6be")
    (org-cite-key :foreground "#79bac4" :underline t)
    (org-code :inherit org-block :foreground "#da8548")
    (org-date :foreground "#ECBE7B")
    (org-default :inherit variable-pitch)
    (org-document-info :foreground "#c678dd")
    (org-document-title :foreground "#c678dd" :weight bold)
    (org-done :inherit org-headline-done :strike-through unspecified :weight bold)
    (org-drawer :foreground "#5B6268")
    (org-ellipsis :foreground "#5B6268" :underline unspecified)
    (org-footnote :foreground "#da8548")
    (org-formula :foreground "#46D9FF")
    (org-habit-alert-face :weight bold :background "#867153")
    (org-habit-alert-future-face :weight bold :background "#5d5243")
    (org-habit-clear-face :weight bold :background "#3f444a")
    (org-habit-clear-future-face :weight bold :background "#23272e")
    (org-habit-overdue-face :weight bold :background "#90484b")
    (org-habit-overdue-future-face :weight bold :background "#63393e")
    (org-habit-ready-face :weight bold :background "#38698d")
    (org-habit-ready-future-face :weight bold :background "#2f4d65")
    (org-headline-done :foreground "#5B6268")
    (org-hide :foreground "#282c34")
    (org-journal-calendar-entry-face :foreground "#c678dd" :slant italic)
    (org-journal-calendar-scheduled-face :foreground "#ff6c6b" :slant italic)
    (org-journal-highlight :foreground "#51afef")
    (org-latex-and-related :foreground "#DFDFDF" :weight bold)
    (org-link :inherit link :foreground "#51afef")
    (org-list-dt :foreground "#51afef")
    (org-meta-line :foreground "#83898d")
    (org-pomodoro-mode-line :foreground "#ff6c6b")
    (org-pomodoro-mode-line-overtime :foreground "#ECBE7B" :weight bold)
    (org-priority :foreground "#ff6c6b")
    (org-property-value :foreground "#83898d")
    (org-quote :inherit org-block :slant italic)
    (org-ref-acronym-face :foreground "#a9a1e1")
    (org-ref-cite-face :foreground "#ECBE7B" :weight light :underline t)
    (org-ref-glossary-face :foreground "#c678dd")
    (org-ref-label-face :foreground "#51afef")
    (org-ref-ref-face :inherit link :foreground "#4db5bd")
    (org-scheduled :foreground "#bbc2cf")
    (org-scheduled-previously :foreground "#DFDFDF")
    (org-scheduled-today :foreground "#9ca0a4")
    (org-sexp-date :foreground "#bbc2cf")
    (org-special-keyword :foreground "#83898d")
    (org-table :foreground "#a9a1e1")
    (org-tag :foreground "#83898d" :weight normal)
    (org-time-grid :foreground "#5B6268")
    (org-todo :foreground "#98be65" :bold inherit)
    (org-upcoming-deadline :foreground "#9da4b0")
    (org-upcoming-distant-deadline :foreground "#717781")
    (org-verbatim :foreground "#98be65")
    (org-warning :foreground "#ECBE7B")
    (outline-1 :foreground "#51afef" :weight bold :extend t)
    (outline-2 :foreground "#c678dd" :weight bold :extend t)
    (outline-3 :foreground "#a9a1e1" :weight bold :extend t)
    (outline-4 :foreground "#7cc3f3" :weight bold :extend t)
    (outline-5 :foreground "#d499e5" :weight bold :extend t)
    (outline-6 :foreground "#a8d7f7" :weight bold :extend t)
    (outline-7 :foreground "#e2bbee" :weight bold :extend t)
    (outline-8 :foreground "#dceffb" :weight bold :extend t)
    (paren-face :foreground "#5B6268")
    (paren-face-match :foreground "#ff6c6b" :background "#1B2229" :weight ultra-bold)
    (paren-face-mismatch :foreground "#1B2229" :background "#ff6c6b" :weight ultra-bold)
    (paren-face-no-match :inherit paren-face-mismatch :weight ultra-bold)
    (parinfer-pretty-parens:dim-paren-face :foreground "#5B6268")
    (parinfer-smart-tab:indicator-face :foreground "#5B6268")
    (persp-face-lighter-buffer-not-in-persp :foreground "#83898d")
    (persp-face-lighter-default :foreground "#51afef" :weight bold)
    (persp-face-lighter-nil-persp :foreground "#5B6268")
    (persp-selected-face :foreground "#51afef" :weight bold)
    (pkgbuild-error-face :underline (:style wave :color "#ff6c6b"))
    (popup-face :inherit tooltip)
    (popup-selection-face :background "#2257A0")
    (popup-tip-face :inherit popup-face :foreground "#a9a1e1" :background "#1B2229")
    (powerline-active0 :inherit mode-line :background "#282c34")
    (powerline-active1 :inherit mode-line :background "#2d3139")
    (powerline-active2 :inherit mode-line :foreground "#DFDFDF" :background "#393c44")
    (powerline-inactive0 :inherit mode-line-inactive :background "#202328")
    (powerline-inactive1 :inherit mode-line-inactive :background "#24272c")
    (powerline-inactive2 :inherit mode-line-inactive :background "#282b30")
    (rainbow-delimiters-base-error-face :inherit rainbow-delimiters-base-face :foreground "#ff6c6b")
    (rainbow-delimiters-base-face :inherit default)
    (rainbow-delimiters-depth-1-face :foreground "#51afef")
    (rainbow-delimiters-depth-2-face :foreground "#c678dd")
    (rainbow-delimiters-depth-3-face :foreground "#98be65")
    (rainbow-delimiters-depth-4-face :foreground "#a9a1e1")
    (rainbow-delimiters-depth-5-face :foreground "#4db5bd")
    (rainbow-delimiters-depth-6-face :foreground "#51afef")
    (rainbow-delimiters-depth-7-face :foreground "#c678dd")
    (rainbow-delimiters-depth-8-face :foreground "#98be65")
    (rainbow-delimiters-depth-9-face :foreground "#a9a1e1")
    (rainbow-delimiters-mismatched-face :inherit rainbow-delimiters-unmatched-face)
    (rainbow-delimiters-unmatched-face :foreground "#ff6c6b" :weight bold :inverse-video t)
    (reb-match-0 :foreground "#da8548" :inverse-video t)
    (reb-match-1 :foreground "#c678dd" :inverse-video t)
    (reb-match-2 :foreground "#98be65" :inverse-video t)
    (reb-match-3 :foreground "#ECBE7B" :inverse-video t)
    (region :background "#42444a" :distant-foreground "#959ba5" :extend t)
    (rjsx-attr :foreground "#da8548")
    (rjsx-tag :foreground "#ff6c6b")
    (rpm-spec-dir-face :foreground "#98be65")
    (rpm-spec-doc-face :foreground "#da8548")
    (rpm-spec-ghost-face :foreground "#5B6268")
    (rpm-spec-macro-face :foreground "#ECBE7B")
    (rpm-spec-obsolete-tag-face :foreground "#ff6c6b")
    (rpm-spec-package-face :foreground "#da8548")
    (rpm-spec-section-face :foreground "#c678dd")
    (rpm-spec-tag-face :foreground "#51afef")
    (rpm-spec-var-face :foreground "#a9a1e1")
    (rst-block :inherit font-lock-constant-face)
    (rst-level-1 :inherit rst-adornment :weight bold)
    (rst-level-2 :inherit rst-adornment :weight bold)
    (rst-level-3 :inherit rst-adornment :weight bold)
    (rst-level-4 :inherit rst-adornment :weight bold)
    (rst-level-5 :inherit rst-adornment :weight bold)
    (rst-level-6 :inherit rst-adornment :weight bold)
    (secondary-selection :background "#3f444a" :extend t)
    (selectrum-current-candidate :background "#42444a" :extend t)
    (sh-heredoc :inherit font-lock-string-face :weight normal)
    (sh-quoted-exec :inherit font-lock-preprocessor-face)
    (shadow :foreground "#5B6268")
    (show-paren-match :foreground "#ff6c6b" :background "#1B2229" :weight ultra-bold)
    (show-paren-mismatch :foreground "#1B2229" :background "#ff6c6b" :weight ultra-bold)
    (smerge-base :background "#304659")
    (smerge-lower :background "#3e493d")
    (smerge-markers :background "#5B6268" :foreground "#282c34" :distant-foreground "#bbc2cf" :weight bold)
    (smerge-mine :background "#4f343a")
    (smerge-other :background "#3e493d")
    (smerge-refined-added :inherit diff-added :inverse-video t)
    (smerge-refined-removed :inherit diff-removed :inverse-video t)
    (smerge-upper :background "#4f343a")
    (sml/charging :foreground "#98be65")
    (sml/discharging :foreground "#ECBE7B" :weight bold)
    (sml/filename :foreground "#a9a1e1" :weight bold)
    (sml/git :foreground "#51afef")
    (sml/modified :foreground "#46D9FF")
    (sml/outside-modified :foreground "#46D9FF")
    (sml/process :weight bold)
    (sml/read-only :foreground "#46D9FF")
    (sml/sudo :foreground "#da8548" :weight bold)
    (sml/vc-edited :foreground "#98be65")
    (solaire-default-face :inherit default :background "#21242b")
    (solaire-hl-line-face :inherit hl-line :background "#282c34" :extend t)
    (solaire-mode-line-face :inherit mode-line :background "#1c1e24" :box unspecified)
    (solaire-mode-line-inactive-face :inherit mode-line-inactive :background "#1d2026" :box unspecified)
    (solaire-org-hide-face :inherit org-hide :foreground "#21242b")
    (sp-pair-overlay-face :background "#42444a")
    (sp-show-pair-match-face :foreground "#ff6c6b" :background "#1B2229" :weight ultra-bold)
    (sp-show-pair-mismatch-face :foreground "#1B2229" :background "#ff6c6b" :weight ultra-bold)
    (spaceline-evil-emacs :background "#46D9FF")
    (spaceline-evil-insert :background "#98be65")
    (spaceline-evil-motion :background "#c678dd")
    (spaceline-evil-normal :background "#51afef")
    (spaceline-evil-replace :background "#da8548")
    (spaceline-evil-visual :background "#3f444a")
    (spaceline-flycheck-error :inherit error :distant-background "#1B2229")
    (spaceline-flycheck-info :inherit success :distant-background "#1B2229")
    (spaceline-flycheck-warning :inherit warning :distant-background "#1B2229")
    (spaceline-highlight-face :background "#51afef")
    (spaceline-modified :background "#da8548")
    (spaceline-python-venv :foreground "#c678dd" :distant-foreground "#a9a1e1")
    (spaceline-unmodified :background "#a9a1e1")
    (spell-fu-incorrect-face :inherit error :underline t)
    (stripe-highlight :background "#5B6268")
    (success :foreground "#98be65")
    (swiper-line-face :background "#51afef" :foreground "#1B2229")
    (swiper-match-face-1 :background "#1B2229" :foreground "#5B6268")
    (swiper-match-face-2 :background "#da8548" :foreground "#1B2229" :weight bold)
    (swiper-match-face-3 :background "#c678dd" :foreground "#1B2229" :weight bold)
    (swiper-match-face-4 :background "#98be65" :foreground "#1B2229" :weight bold)
    (symbol-overlay-default-face :background "#54565c" :distant-foreground "#5B6268")
    (symbol-overlay-face-1 :background "#38607e" :distant-foreground "#5B6268")
    (symbol-overlay-face-2 :background "#5b5a79" :distant-foreground "#5B6268")
    (symbol-overlay-face-3 :background "#625749" :distant-foreground "#5B6268")
    (symbol-overlay-face-4 :background "#5d4639" :distant-foreground "#5B6268")
    (symbol-overlay-face-5 :background "#683f44" :distant-foreground "#5B6268")
    (symbol-overlay-face-6 :background "#574266" :distant-foreground "#5B6268")
    (symbol-overlay-face-7 :background "#546647" :distant-foreground "#5B6268")
    (symbol-overlay-face-8 :background "#2e4e5c" :distant-foreground "#5B6268")
    (tab-bar :background "#21242b" :foreground "#21242b" :box unspecified)
    (tab-bar-tab :background "#282c34" :foreground "#bbc2cf" :box unspecified)
    (tab-bar-tab-inactive :background "#21242b" :foreground "#5B6268" :box unspecified)
    (tab-line :background "#21242b" :foreground "#21242b" :box unspecified)
    (tab-line-close-highlight :foreground "#51afef")
    (tab-line-highlight :inherit tab-line-tab)
    (tab-line-tab :background "#282c34" :foreground "#bbc2cf" :box unspecified)
    (tab-line-tab-current :background "#282c34" :foreground "#bbc2cf")
    (tab-line-tab-inactive :background "#21242b" :foreground "#5B6268" :box unspecified)
    (tab-line-tab-inactive-alternate :background "#21242b" :foreground "#5B6268" :box unspecified)
    (tabbar-button :foreground "#bbc2cf" :background "#282c34")
    (tabbar-button-highlight :inherit tabbar-button :inverse-video t)
    (tabbar-default :foreground "#282c34" :background "#282c34" :height 1.0)
    (tabbar-highlight :foreground "#bbc2cf" :background "#2257A0" :distant-foreground "#282c34")
    (tabbar-modified :inherit tabbar-default :foreground "#ff6c6b" :weight bold)
    (tabbar-selected :inherit tabbar-default :weight bold :foreground "#bbc2cf" :background "#21242b")
    (tabbar-selected-modified :inherit tabbar-selected :foreground "#98be65")
    (tabbar-unselected :inherit tabbar-default :foreground "#5B6268")
    (tabbar-unselected-modified :inherit tabbar-modified)
    (telephone-line-accent-active :foreground "#bbc2cf" :background "#3f444a")
    (telephone-line-accent-inactive :foreground "#bbc2cf" :background "#202328")
    (telephone-line-evil :foreground "#bbc2cf" :weight bold)
    (telephone-line-evil-emacs :background "#775188" :weight bold)
    (telephone-line-evil-insert :background "#60754c" :weight bold)
    (telephone-line-evil-motion :background "#3c6d91" :weight bold)
    (telephone-line-evil-normal :background "#934c4f" :weight bold)
    (telephone-line-evil-operator :background "#68668a" :weight bold)
    (telephone-line-evil-replace :background "#21242b" :weight bold)
    (telephone-line-evil-visual :background "#81583e" :weight bold)
    (telephone-line-projectile :foreground "#98be65")
    (term :foreground "#bbc2cf")
    (term-bold :weight bold)
    (term-color-black :background "#1B2229" :foreground "#1B2229")
    (term-color-blue :background "#51afef" :foreground "#51afef")
    (term-color-cyan :background "#46D9FF" :foreground "#46D9FF")
    (term-color-green :background "#98be65" :foreground "#98be65")
    (term-color-magenta :background "#c678dd" :foreground "#c678dd")
    (term-color-red :background "#ff6c6b" :foreground "#ff6c6b")
    (term-color-white :background "#DFDFDF" :foreground "#DFDFDF")
    (term-color-yellow :background "#ECBE7B" :foreground "#ECBE7B")
    (terraform--resource-name-face :foreground "#98be65")
    (terraform--resource-type-face :foreground "#ECBE7B")
    (tldr-code-block :foreground "#98be65" :background "#42444a" :weight semi-bold)
    (tldr-command-argument :foreground "#bbc2cf" :background "#42444a")
    (tldr-command-itself :foreground "#282c34" :background "#98be65" :weight semi-bold)
    (tldr-description :foreground "#bbc2cf" :weight semi-bold)
    (tldr-introduction :foreground "#4894c9" :weight semi-bold)
    (tldr-title :foreground "#ECBE7B" :bold t :height 1.4)
    (tooltip :background "#21242b" :foreground "#bbc2cf")
    (trailing-whitespace :background "#ff6c6b")
    (treemacs-directory-face :foreground "#bbc2cf")
    (treemacs-file-face :foreground "#bbc2cf")
    (treemacs-fringe-indicator-face :foreground "#51afef")
    (treemacs-git-added-face :foreground "#98be65")
    (treemacs-git-conflict-face :foreground "#ff6c6b")
    (treemacs-git-modified-face :foreground "#a9a1e1")
    (treemacs-git-untracked-face :inherit font-lock-doc-face)
    (treemacs-nerd-icons-file-face :foreground "#83898d")
    (treemacs-nerd-icons-root-face :inherit font-lock-string-face :weight bold :height 1.2)
    (treemacs-on-failure-pulse-face :foreground "#1B2229" :background "#ff6c6b" :extend t)
    (treemacs-on-success-pulse-face :foreground "#1B2229" :background "#98be65" :extend t)
    (treemacs-root-face :inherit font-lock-string-face :weight bold :height 1.2)
    (treemacs-tags-face :foreground "#51afef")
    (ts-fold-replacement-face :inherit font-lock-comment-face :weight light :background "#22252c" :box (:line-width -1 :style released-button))
    (ts-fold-replacement-mouse-face :inherit font-lock-comment-face :weight light :background "#22252c" :box (:line-width -1 :style released-button))
    (twitter-divider :underline (:color "#46484c"))
    (typescript-jsdoc-tag :foreground "#83898d")
    (typescript-jsdoc-type :foreground "#6f7477")
    (typescript-jsdoc-value :foreground "#959a9e")
    (undo-tree-visualizer-active-branch-face :foreground "#51afef")
    (undo-tree-visualizer-current-face :foreground "#98be65" :weight bold)
    (undo-tree-visualizer-default-face :foreground "#5B6268")
    (undo-tree-visualizer-register-face :foreground "#ECBE7B")
    (undo-tree-visualizer-unmodified-face :foreground "#5B6268")
    (vertical-border :background "#191b20" :foreground "#191b20")
    (vertico-current :background "#42444a" :extend t)
    (vertico-posframe-border :background "#3f444a")
    (vertico-posframe-border-2 :background "#ff6c6b")
    (vertico-posframe-border-3 :background "#98be65")
    (vertico-posframe-border-4 :background "#51afef")
    (vertico-posframe-border-fallback :background "#ECBE7B")
    (vhl/default-face :background "#3f444a")
    (vimish-fold-fringe :foreground "#c678dd")
    (vimish-fold-overlay :inherit font-lock-comment-face :background "#1B2229" :weight light)
    (vr/group-0 :background "#51afef" :foreground "#282c34")
    (vr/group-1 :background "#c678dd" :foreground "#282c34")
    (vr/group-2 :background "#98be65" :foreground "#282c34")
    (vr/match-0 :background "#3e493d" :foreground "#bbc2cf")
    (vr/match-1 :background "#546647" :foreground "#bbc2cf")
    (vr/match-separator-face :inherit bold :foreground "#ff6c6b")
    (vterm-color-black :background "#54595e" :foreground "#1B2229")
    (vterm-color-blue :background "#7cc3f3" :foreground "#51afef")
    (vterm-color-cyan :background "#74e2ff" :foreground "#46D9FF")
    (vterm-color-green :background "#b1ce8b" :foreground "#98be65")
    (vterm-color-magenta :background "#d499e5" :foreground "#c678dd")
    (vterm-color-red :background "#ff9090" :foreground "#ff6c6b")
    (vterm-color-white :background "#e7e7e7" :foreground "#DFDFDF")
    (vterm-color-yellow :background "#f0ce9c" :foreground "#ECBE7B")
    (warning :foreground "#ECBE7B")
    (web-mode-block-control-face :foreground "#da8548")
    (web-mode-block-delimiter-face :foreground "#c678dd")
    (web-mode-css-property-name-face :foreground "#ECBE7B")
    (web-mode-doctype-face :foreground "#5B6268")
    (web-mode-html-attr-name-face :foreground "#ECBE7B")
    (web-mode-html-attr-value-face :foreground "#98be65")
    (web-mode-html-entity-face :foreground "#46D9FF" :inherit italic)
    (web-mode-html-tag-bracket-face :foreground "#51afef")
    (web-mode-html-tag-face :foreground "#46D9FF")
    (web-mode-json-context-face :foreground "#98be65")
    (web-mode-json-key-face :foreground "#98be65")
    (web-mode-keyword-face :foreground "#51afef")
    (web-mode-string-face :foreground "#98be65")
    (web-mode-type-face :foreground "#ECBE7B")
    (wg-brace-face :foreground "#51afef")
    (wg-current-workgroup-face :foreground "#1B2229" :background "#51afef")
    (wg-divider-face :foreground "#3f444a")
    (wg-other-workgroup-face :foreground "#5B6268")
    (wgrep-delete-face :foreground "#23272e" :background "#ff6c6b")
    (wgrep-done-face :foreground "#51afef")
    (wgrep-face :weight bold :foreground "#98be65" :background "#5B6268")
    (wgrep-file-face :foreground "#5B6268")
    (wgrep-reject-face :foreground "#ff6c6b" :weight bold)
    (which-func :foreground "#51afef")
    (which-key-command-description-face :foreground "#51afef")
    (which-key-group-description-face :foreground "#a9a1e1")
    (which-key-key-face :foreground "#98be65")
    (which-key-local-map-description-face :foreground "#c678dd")
    (whitespace-empty :background "#23272e")
    (whitespace-indentation :foreground "#3f444a" :background "#23272e")
    (whitespace-line :background "#1B2229" :foreground "#ff6c6b" :weight bold)
    (whitespace-newline :foreground "#3f444a")
    (whitespace-space :foreground "#3f444a")
    (whitespace-tab :foreground "#3f444a" :background unspecified)
    (whitespace-trailing :inherit trailing-whitespace)
    (widget-button-pressed :foreground "#ff6c6b")
    (widget-documentation :foreground "#98be65")
    (widget-field :background "#23272e" :distant-foreground "#282c34" :box (:line-width -1 :color "#3f444a") :extend t)
    (widget-single-line-field :background "#23272e" :distant-foreground "#282c34")
    (window-divider :inherit vertical-border)
    (window-divider-first-pixel :inherit window-divider)
    (window-divider-last-pixel :inherit window-divider)
    (window-tool-bar-button :background "#282c34" :foreground "#bbc2cf")
    (window-tool-bar-button-disabled :background "#21242b" :foreground "#5B6268")
    (window-tool-bar-button-hover :inherit highlight :distant-foreground "#282c34")
    (winum-face :inherit bold :foreground "#51afef")
    (woman-bold :inherit Man-overstrike)
    (woman-italic :inherit Man-underline)
    (xah-elisp-at-symbol :inherit font-lock-warning-face)
    (xah-elisp-cap-variable :inherit font-lock-preprocessor-face)
    (xah-elisp-command-face :inherit font-lock-type-face)
    (xah-elisp-dollar-symbol :inherit font-lock-variable-name-face)
    (xref-file-header :inherit success)
    (xref-line-number :foreground "#51afef")
    (xref-match :foreground "#98be65" :background "#1B2229" :weight bold)
    (yas-field-highlight-face :inherit match)))

;; 用 face-spec-set 而不是 set-face-attribute,三个理由:
;;   1. 这张表覆盖 1200+ face,其中大多数(cider-*、jdee-* …)对应的包本机没装,
;;      set-face-attribute 撞上未定义的 face 会直接报错;
;;   2. `(t ATTRS)' 不带 display 条件,batch 的 tty 帧下必然命中 —— 正是
;;      主题自带 spec 在这里失效的原因;
;;   3. face-override-spec 的优先级高于 defface,org 在 fontify 时才 autoload
;;      sh-script / conf-mode,它们的 defface 不会把这里的值盖回去。
;; :weight/:slant/:underline 显式置空:默认 face 靠字形而非颜色区分,
;; 主题只覆盖它显式声明的属性,不重置就会有多余的 bold/italic 混进产物。
(pcase-dolist (`(,face . ,attrs) blog-doom-one-faces)
  (unless (facep face) (make-empty-face face))
  (face-spec-set face `((t ,(append '(:weight normal :slant normal
                                      :underline nil :box nil)
                                    attrs)))
                 'face-override-spec))

(provide 'doom-one-faces)
;;; doom-one-faces.el ends here
